---
name: Windows

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: configure
        run: cmake -S . -B build

      - name: build
        run: cmake --build build

      - name: test
        run: |
          cd build
          make && ctest
